### PR TITLE
use PyProjectTOML from poetry instead of poetry-core

### PR DESCRIPTION
**Pull request by dotlambda**
Otherwise tests fail with

    AttributeError: 'PyProjectTOML' object has no attribute 'file'

### CODE REVIEW

**Comment by mousabaker** [comment]
> Otherwise tests fail with
> 
> ```
> AttributeError: 'PyProjectTOML' object has no attribute 'file'
> ```

Can you elaborate more on when this happens? Its been working fine for a long time.

**Comment by dotlambda** [comment]
<details>

<summary>It happens when running the tests under poetry 1.5.</summary>

```
============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-7.2.1, pluggy-1.0.0
rootdir: /build/source
plugins: mock-3.10.0
collected 34 items

tests/e2e/test_e2e.py EEEEEE                                             [ 17%]
tests/integration/test_integration.py ..                                 [ 23%]
tests/unit/test_unit.py ..........................                       [100%]

==================================== ERRORS ====================================
________________________ ERROR at setup of test_command ________________________

project_path = PosixPath('/build/source/tests/fixtures/simple_project')

    @pytest.fixture(scope="function")
    def pyproject_content(project_path: Path) -> TOMLDocument:
        path = project_path / "pyproject.toml"
>       return PyProjectTOML(path).file.read()
E       AttributeError: 'PyProjectTOML' object has no attribute 'file'

tests/conftest.py:25: AttributeError
__________________ ERROR at setup of test_command_with_latest __________________

project_path = PosixPath('/build/source/tests/fixtures/simple_project')

    @pytest.fixture(scope="function")
    def pyproject_content(project_path: Path) -> TOMLDocument:
        path = project_path / "pyproject.toml"
>       return PyProjectTOML(path).file.read()
E       AttributeError: 'PyProjectTOML' object has no attribute 'file'

tests/conftest.py:25: AttributeError
_________________ ERROR at setup of test_command_with_dry_run __________________

project_path = PosixPath('/build/source/tests/fixtures/simple_project')

    @pytest.fixture(scope="function")
    def pyproject_content(project_path: Path) -> TOMLDocument:
        path = project_path / "pyproject.toml"
>       return PyProjectTOML(path).file.read()
E       AttributeError: 'PyProjectTOML' object has no attribute 'file'

tests/conftest.py:25: AttributeError
________________ ERROR at setup of test_command_with_no_install ________________

project_path = PosixPath('/build/source/tests/fixtures/simple_project')

    @pytest.fixture(scope="function")
    def pyproject_content(project_path: Path) -> TOMLDocument:
        path = project_path / "pyproject.toml"
>       return PyProjectTOML(path).file.read()
E       AttributeError: 'PyProjectTOML' object has no attribute 'file'

tests/conftest.py:25: AttributeError
__________ ERROR at setup of test_command_reverts_pyproject_on_error ___________

project_path = PosixPath('/build/source/tests/fixtures/simple_project')

    @pytest.fixture(scope="function")
    def pyproject_content(project_path: Path) -> TOMLDocument:
        path = project_path / "pyproject.toml"
>       return PyProjectTOML(path).file.read()
E       AttributeError: 'PyProjectTOML' object has no attribute 'file'

tests/conftest.py:25: AttributeError
______________ ERROR at setup of test_pinned_without_latest_fails ______________

project_path = PosixPath('/build/source/tests/fixtures/simple_project')

    @pytest.fixture(scope="function")
    def pyproject_content(project_path: Path) -> TOMLDocument:
        path = project_path / "pyproject.toml"
>       return PyProjectTOML(path).file.read()
E       AttributeError: 'PyProjectTOML' object has no attribute 'file'

tests/conftest.py:25: AttributeError
=========================== short test summary info ============================
ERROR tests/e2e/test_e2e.py::test_command - AttributeError: 'PyProjectTOML' object has no attribute 'file'
ERROR tests/e2e/test_e2e.py::test_command_with_latest - AttributeError: 'PyProjectTOML' object has no attribute 'file'
ERROR tests/e2e/test_e2e.py::test_command_with_dry_run - AttributeError: 'PyProjectTOML' object has no attribute 'file'
ERROR tests/e2e/test_e2e.py::test_command_with_no_install - AttributeError: 'PyProjectTOML' object has no attribute 'file'
ERROR tests/e2e/test_e2e.py::test_command_reverts_pyproject_on_error - AttributeError: 'PyProjectTOML' object has no attribute 'file'
ERROR tests/e2e/test_e2e.py::test_pinned_without_latest_fails - AttributeError: 'PyProjectTOML' object has no attribute 'file'
========================= 28 passed, 6 errors in 0.60s =========================
```

</details>

See these two commits:
https://github.com/python-poetry/poetry-core/commit/2ebc219c2b5def310c3476708ea8f39cae3f97c7#diff-11c2cc75ee2d591ac0a1551902223d5f593d66ffef0787e5a2b608e59ce2ac83
https://github.com/python-poetry/poetry/commit/c89e994eead3fa56f573cc08276f3e8ad74f6e02#diff-269ff75bf40ae16792f5de1d7c8a14f27a24beba045f1d05ae540c69c0a60972

**Comment by dotlambda** [comment]
<details>

<summary>It happens when running the tests under poetry 1.5.</summary>

```
============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-7.2.1, pluggy-1.0.0
rootdir: /build/source
plugins: mock-3.10.0
collected 34 items

tests/e2e/test_e2e.py EEEEEE                                             [ 17%]
tests/integration/test_integration.py ..                                 [ 23%]
tests/unit/test_unit.py ..........................                       [100%]

==================================== ERRORS ====================================
________________________ ERROR at setup of test_command ________________________

project_path = PosixPath('/build/source/tests/fixtures/simple_project')

    @pytest.fixture(scope="function")
    def pyproject_content(project_path: Path) -> TOMLDocument:
        path = project_path / "pyproject.toml"
>       return PyProjectTOML(path).file.read()
E       AttributeError: 'PyProjectTOML' object has no attribute 'file'

tests/conftest.py:25: AttributeError
__________________ ERROR at setup of test_command_with_latest __________________

project_path = PosixPath('/build/source/tests/fixtures/simple_project')

    @pytest.fixture(scope="function")
    def pyproject_content(project_path: Path) -> TOMLDocument:
        path = project_path / "pyproject.toml"
>       return PyProjectTOML(path).file.read()
E       AttributeError: 'PyProjectTOML' object has no attribute 'file'

tests/conftest.py:25: AttributeError
_________________ ERROR at setup of test_command_with_dry_run __________________

project_path = PosixPath('/build/source/tests/fixtures/simple_project')

    @pytest.fixture(scope="function")
    def pyproject_content(project_path: Path) -> TOMLDocument:
        path = project_path / "pyproject.toml"
>       return PyProjectTOML(path).file.read()
E       AttributeError: 'PyProjectTOML' object has no attribute 'file'

tests/conftest.py:25: AttributeError
________________ ERROR at setup of test_command_with_no_install ________________

project_path = PosixPath('/build/source/tests/fixtures/simple_project')

    @pytest.fixture(scope="function")
    def pyproject_content(project_path: Path) -> TOMLDocument:
        path = project_path / "pyproject.toml"
>       return PyProjectTOML(path).file.read()
E       AttributeError: 'PyProjectTOML' object has no attribute 'file'

tests/conftest.py:25: AttributeError
__________ ERROR at setup of test_command_reverts_pyproject_on_error ___________

project_path = PosixPath('/build/source/tests/fixtures/simple_project')

    @pytest.fixture(scope="function")
    def pyproject_content(project_path: Path) -> TOMLDocument:
        path = project_path / "pyproject.toml"
>       return PyProjectTOML(path).file.read()
E       AttributeError: 'PyProjectTOML' object has no attribute 'file'

tests/conftest.py:25: AttributeError
______________ ERROR at setup of test_pinned_without_latest_fails ______________

project_path = PosixPath('/build/source/tests/fixtures/simple_project')

    @pytest.fixture(scope="function")
    def pyproject_content(project_path: Path) -> TOMLDocument:
        path = project_path / "pyproject.toml"
>       return PyProjectTOML(path).file.read()
E       AttributeError: 'PyProjectTOML' object has no attribute 'file'

tests/conftest.py:25: AttributeError
=========================== short test summary info ============================
ERROR tests/e2e/test_e2e.py::test_command - AttributeError: 'PyProjectTOML' object has no attribute 'file'
ERROR tests/e2e/test_e2e.py::test_command_with_latest - AttributeError: 'PyProjectTOML' object has no attribute 'file'
ERROR tests/e2e/test_e2e.py::test_command_with_dry_run - AttributeError: 'PyProjectTOML' object has no attribute 'file'
ERROR tests/e2e/test_e2e.py::test_command_with_no_install - AttributeError: 'PyProjectTOML' object has no attribute 'file'
ERROR tests/e2e/test_e2e.py::test_command_reverts_pyproject_on_error - AttributeError: 'PyProjectTOML' object has no attribute 'file'
ERROR tests/e2e/test_e2e.py::test_pinned_without_latest_fails - AttributeError: 'PyProjectTOML' object has no attribute 'file'
========================= 28 passed, 6 errors in 0.60s =========================
```

</details>

See these two commits:
https://github.com/python-poetry/poetry-core/commit/2ebc219c2b5def310c3476708ea8f39cae3f97c7#diff-11c2cc75ee2d591ac0a1551902223d5f593d66ffef0787e5a2b608e59ce2ac83
https://github.com/python-poetry/poetry/commit/c89e994eead3fa56f573cc08276f3e8ad74f6e02#diff-269ff75bf40ae16792f5de1d7c8a14f27a24beba045f1d05ae540c69c0a60972

**Comment by mousabaker** [comment]
I see, thanks for the clarification. The linter is failing due to invalid the commit message, please see [here](https://github.com/MousaZeidBaker/poetry-plugin-up/blob/master/CONTRIBUTING.md#commit-message) on how to fix it.

**Pull request merged**
