### PR TITLE
(🎁) Error on pinned without latest

### LINKED ISSUE #11: (📚) Improve documentation for `--pinned`
I can't figure out what this option does.

 `Included pinned dependencies when updating to latest.` Does that mean this option implies `--latest`? should it be an error to have `--pinned` without `--latest`?

I also think it has a typo, looks like `Included` should be `Include`.

### Edit:
After reading the src code I see that pinned means an exact version and it does depend on `--latest`

### PR DESCRIPTION
**Pull request by KotlinIsland**
- Resolves #11

### CODE REVIEW

**Review by mousabaker — APPROVED** [review]

**Comment by mousabaker** [comment]
Great improvement!

**Review by mousabaker — CHANGES_REQUESTED** [review]
- [ ] Commit message must follow [Conventional Commits](https://www.conventionalcommits.org/) specification, see [Contributing Guide](https://github.com/MousaZeidBaker/poetry-plugin-up/blob/master/CONTRIBUTING.md#commit-message)

```
git commit --amend -m "fix: throw error on pinned without latest"
```

- [ ] Fix other linting errors `src/poetry_plugin_up/command.py:38:81: E501 line too long (87 > 80 characters)`, see [ci logs](https://github.com/MousaZeidBaker/poetry-plugin-up/pull/15/checks)

**Comment by KotlinIsland** [comment]
Why is your line length set to 80? pep 8 says 79, but black defaults to 88 (which I prefer)

**Comment by mousabaker** [comment]
> Why is your line length set to 80? pep 8 says 79, but black defaults to 88 (which I prefer)

80 is the "industry standard" for most programming languages, whether it's 79 or 80, doesn't matter much as long as we are consistent.

**Review by mousabaker — APPROVED** [review]

**Pull request merged**
